<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 1.属性定义 -->
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="radius" value="0.03" />
    <!-- 2.属性调用 -->
    <MyUsePropetryxxx name="${PI}" />
    <MyUsePropetryxxx name="${radius}" />
    <!-- 3.算数运算 -->
    <MyUsePropetryYYY name="${PI / 2}" />
    <MyUsePropetryYYY name="${radius * 2}" />


</robot>