// Generated by gencpp from file plumbing_server_client/ADDInts.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <plumbing_server_client/ADDIntsRequest.h>
#include <plumbing_server_client/ADDIntsResponse.h>


namespace plumbing_server_client
{

struct ADDInts
{

typedef ADDIntsRequest Request;
typedef ADDIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ADDInts
} // namespace plumbing_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_server_client::ADDInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_server_client::ADDInts&) { return value(); }
};

template<>
struct DataType< ::plumbing_server_client::ADDInts > {
  static const char* value()
  {
    return "plumbing_server_client/ADDInts";
  }

  static const char* value(const ::plumbing_server_client::ADDInts&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_server_client::ADDIntsRequest> should match
// service_traits::MD5Sum< ::plumbing_server_client::ADDInts >
template<>
struct MD5Sum< ::plumbing_server_client::ADDIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::ADDInts >::value();
  }
  static const char* value(const ::plumbing_server_client::ADDIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::ADDIntsRequest> should match
// service_traits::DataType< ::plumbing_server_client::ADDInts >
template<>
struct DataType< ::plumbing_server_client::ADDIntsRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::ADDInts >::value();
  }
  static const char* value(const ::plumbing_server_client::ADDIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_server_client::ADDIntsResponse> should match
// service_traits::MD5Sum< ::plumbing_server_client::ADDInts >
template<>
struct MD5Sum< ::plumbing_server_client::ADDIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::ADDInts >::value();
  }
  static const char* value(const ::plumbing_server_client::ADDIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::ADDIntsResponse> should match
// service_traits::DataType< ::plumbing_server_client::ADDInts >
template<>
struct DataType< ::plumbing_server_client::ADDIntsResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::ADDInts >::value();
  }
  static const char* value(const ::plumbing_server_client::ADDIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_ADDINTS_H
